device: cpu

paths:
  output_dir: /mnt/data/sabg/output
  model_weights: /mnt/data/sabg/weights/weights.pth
  annotations_file_path: /mnt/data/sabg/annotations.json
  metrics_file_path: /mnt/data/sabg/metrics.xlsx

filter:
  min_conf: 0.7
  min_area: 200
  remove_ripped: true
  pixel_thr: 0.5

background:
  initial_ring_radius: 40
  patch_radius: 15
  angle_step: 20
  buffer_px: 2
  max_ring_radius: 300
  ring_step: 5

output:
  save_overlay: true
  overlay_draw_background: true
  overlay_draw_id: true

  save_binary_masks: true
  binary_mask_draw_id: true
  binary_mask_draw_background: true

  save_annotations: true
